#if canImport(LocalDictationCore)
import LocalDictationCore
#endif

public func allTests() -> [RegisteredTest] {
    [
        RegisteredTest(name: "cleanup.fillers", body: CleanupSuite.fillers),
        RegisteredTest(name: "cleanup.repeats", body: CleanupSuite.repeats),
        RegisteredTest(name: "cleanup.polishedPunctuation", body: CleanupSuite.polishedPunctuation),
        RegisteredTest(name: "cleanup.emailStyle", body: CleanupSuite.emailStyle),
        RegisteredTest(name: "cleanup.vocabulary", body: CleanupSuite.vocabulary),
        RegisteredTest(name: "cleanup.rawKeepsFillers", body: CleanupSuite.rawKeepsFillers),
        RegisteredTest(name: "cleanup.emptyStaysEmpty", body: CleanupSuite.emptyStaysEmpty),
        RegisteredTest(name: "cleanup.longestVocabWins", body: CleanupSuite.longestVocabWins),
        RegisteredTest(name: "vocab.persist", body: VocabularySuite.persist),
        RegisteredTest(name: "vocab.shortWordsRejected", body: VocabularySuite.shortWordsRejected),
        RegisteredTest(name: "vocab.remove", body: VocabularySuite.remove),
        RegisteredTest(name: "session.readyHoldCycle", body: KeyboardSessionSuite.readyHoldCycle),
        RegisteredTest(name: "session.setupBlocksRecording", body: KeyboardSessionSuite.setupBlocksRecording),
        RegisteredTest(name: "session.emptyAudioFails", body: KeyboardSessionSuite.emptyAudioFails),
        RegisteredTest(name: "session.cancelReturnsIdle", body: KeyboardSessionSuite.cancelReturnsIdle),
        RegisteredTest(name: "session.toggleStartsAndStops", body: KeyboardSessionSuite.toggleStartsAndStops),
        RegisteredTest(name: "session.readinessRecovery", body: KeyboardSessionSuite.readinessRecovery),
        RegisteredTest(name: "session.missingFullAccessStillRecords", body: KeyboardSessionSuite.missingFullAccessStillRecords),
        RegisteredTest(name: "session.failThenRetry", body: KeyboardSessionSuite.failThenRetry),
        RegisteredTest(name: "session.cancelFromTranscribing", body: KeyboardSessionSuite.cancelFromTranscribing),
        RegisteredTest(name: "session.doubleBeginRejected", body: KeyboardSessionSuite.beginHoldWhileRecordingRejected),
        RegisteredTest(name: "session.finishWhileIdle", body: KeyboardSessionSuite.finishWhileIdleDoesNotInsert),
        RegisteredTest(name: "store.roundTrip", body: SharedStoreSuite.roundTrip),
        RegisteredTest(name: "store.missingFileIsIdle", body: SharedStoreSuite.missingFileIsIdle),
        RegisteredTest(name: "store.clipboardRoundTrip", body: SharedStoreSuite.clipboardRoundTrip),
        RegisteredTest(name: "pipeline.insertsCleanedText", body: PipelineSuite.insertsCleanedText),
        RegisteredTest(name: "pipeline.rejectsBlank", body: PipelineSuite.rejectsBlank),
        RegisteredTest(name: "pipeline.prependsSpaceWhenNeeded", body: PipelineSuite.prependsSpaceWhenNeeded),
        RegisteredTest(name: "pipeline.noSpaceAfterPunctuation", body: PipelineSuite.noSpaceAfterPunctuation),
        RegisteredTest(name: "pipeline.noSpaceAtStart", body: PipelineSuite.noSpaceAtStart),
        RegisteredTest(name: "pipeline.noSpaceAfterNewline", body: PipelineSuite.noSpaceAfterNewline),
        RegisteredTest(name: "pipeline.spaceAfterLetter", body: PipelineSuite.spaceAfterLetter),
        RegisteredTest(name: "pipeline.doubleEmailWrap", body: PipelineSuite.doubleEmailWrapIsWrong),
        RegisteredTest(name: "pipeline.polishedIdempotent", body: PipelineSuite.polishedIdempotent),
        RegisteredTest(name: "readiness.blockingOrder", body: ReadinessSuite.blockingOrder),
        RegisteredTest(name: "capture.errorCopy", body: CaptureSuite.errorCopy),
        RegisteredTest(name: "host.idleStartClipFails", body: HostCaptureSuite.idleStartClipFailsWithoutHardware),
        RegisteredTest(name: "host.backgroundStartIllegal", body: HostCaptureSuite.backgroundStartSessionIsIllegal),
        RegisteredTest(name: "host.foregroundArmsHardware", body: HostCaptureSuite.foregroundStartSessionArmsHardware),
        RegisteredTest(name: "host.clipDoesNotStartHardware", body: HostCaptureSuite.startClipOnLiveOpensClipNotHardware),
        RegisteredTest(name: "host.doubleStartClipRejected", body: HostCaptureSuite.doubleStartClipRejected),
        RegisteredTest(name: "host.stopBeforeStart", body: HostCaptureSuite.stopBeforeStartIsNotClipping),
        RegisteredTest(name: "host.stopKeepsHardware", body: HostCaptureSuite.stopClipKeepsHardwareForNextTake),
        RegisteredTest(name: "host.emptyStaysLive", body: HostCaptureSuite.emptyTranscriptStaysLive),
        RegisteredTest(name: "host.failKeepsSession", body: HostCaptureSuite.failedTranscriptDoesNotKillSession),
        RegisteredTest(name: "host.micOff", body: HostCaptureSuite.micOffStopsHardwareFromAnyPhase),
        RegisteredTest(name: "host.secondStartNoRestart", body: HostCaptureSuite.secondForegroundStartDoesNotRestartHardware),
        RegisteredTest(name: "host.httpRoutes", body: HostCaptureSuite.httpRoutes),
        RegisteredTest(name: "host.clipDuringTranscribe", body: HostCaptureSuite.startClipDuringTranscribingIsRejected),
        RegisteredTest(name: "host.micOffDuringTranscribe", body: HostCaptureSuite.micOffDuringTranscribing),
        RegisteredTest(name: "host.lastErrorClears", body: HostCaptureSuite.lastErrorClearsOnNextClip),
        RegisteredTest(name: "host.finishAfterMicOff", body: HostCaptureSuite.finishAfterMicOffStaysIdle),
        RegisteredTest(name: "host.twoTakeCycle", body: HostCaptureSuite.fullTapCycleTwice),
        RegisteredTest(name: "host.stopFromIdle", body: HostCaptureSuite.stopFromIdleDoesNotArm),
    ]
}
